### ISSUE TITLE
What happened？

### ISSUE THREAD

**Issue by mgfjxxiexiaolong** [realdennis/xvideo-js#2]
```
/usr/local/lib/node_modules/xvideo-js/xvideo/ctrl.js:14
	obj.nextPage = async function(){
	                     ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/xvideo-js/xvideo/listen.js:1:74)
    at Module._compile (module.js:571:32)
```

<img width="585" alt="qq20180521-100745 2x" src="https://user-images.githubusercontent.com/13596540/40287298-fb0c5aa4-5c71-11e8-9a8a-17de5406e1ac.png">

**Comment by realdennis** [comment]
What's your Node version ?
Async functions are not supported by Node versions older than version 7.6 .

**Comment by realdennis** [comment]
Hey I update it to version 1.4, and support older node version using babel.
You can try it .
